vim.opt.encoding = 'utf-8';
vim.opt.fileencoding = 'utf-8'
vim.opt.title = true
vim.opt.backup = false
vim.opt.clipboard = 'unnamedplus'
vim.opt.cmdheight = 2
vim.opt.completeopt = { 'menuone', 'noselect' }
vim.optconceallevel = 0
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.mouse = 'a'
vim.opt.pumheight = 10
vim.opt.showmode = false
vim.opt.showtabline = 2
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.swapfile = false
vim.opt.termguicolors = true
vim.opt.timeoutlen = 300
vim.opt.undofile = true
vim.opt.updatetime = 300
vim.opt.writebackup = false
vim.opt.shell = 'zsh'
vim.opt.expandtab = true
vim.opt.shiftwidth = 4
vim.opt.tabstop = 4
vim.opt.cursorline = false
vim.opt.number = true
vim.opt.relativenumber = false
vim.opt.numberwidth = 4
vim.opt.wrap = false
vim.opt.winblend = 20
vim.opt.wildoptions = 'pum'
vim.opt.virtualedit = 'onemore'
vim.opt.pumblend = 20
vim.opt.background = 'light'
vim.opt.scrolloff = 8
vim.opt.sidescrolloff = 8
vim.opt.guifont = 'Hack Nerd Font Regular:h10'
vim.opt.splitbelow = false -- オンのとき、ウィンドウを横分割すると新しいウィンドウはカレントウィンドウの下に開かれる
vim.opt.splitright = false -- オンのとき、ウィンドウを縦分割すると新しいウィンドウはカレントウィンドウの右に開かれる
